export const FETCH_SCHEDULE_REQUEST = 'app/Schedule/FETCH_SCHEDULE_REQUEST';
export const FETCH_SCHEDULE_SUCCESS = 'app/Schedule/FETCH_SCHEDULE_SUCCESS';
export const FETCH_SCHEDULE_FAILURE = 'app/Schedule/FETCH_SCHEDULE_FAILURE';
