export const FETCH_GRADES_REQUEST = 'app/Grades/FETCH_GRADES_REQUEST';
export const FETCH_GRADES_SUCCESS = 'app/Grades/FETCH_GRADES_SUCCESS';
export const FETCH_GRADES_FAILURE = 'app/Grades/FETCH_GRADES_FAILURE';

export const CREATE_GRADE_REQUEST = 'app/Grades/CREATE_GRADE_REQUEST';
export const CREATE_GRADE_SUCCESS = 'app/Grades/CREATE_GRADE_SUCCESS';
export const CREATE_GRADE_FAILURE = 'app/Grades/CREATE_GRADE_FAILURE';
