export const FETCH_GROUP_REQUEST = 'app/Group/FETCH_GROUP_REQUEST';
export const FETCH_GROUP_SUCCESS = 'app/Group/FETCH_GROUP_SUCCESS';
export const FETCH_GROUP_FAILURE = 'app/Group/FETCH_GROUP_FAILURE';

export const FETCH_STUDENTS_REQUEST = 'app/Students/FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'app/Students/FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'app/Students/FETCH_STUDENTS_FAILURE';
